image: alpine/edge
packages:
  - hut
sources:
  - git@git.sr.ht:~fmrsn/citools
  - git@git.sr.ht:~fmrsn/fmrsn.com
secrets:
  - 270fb008-0636-482b-880e-d6c2472ada6c
oauth: pages.sr.ht/PAGES:RW
environment:
  PATH: /bin:/usr/bin:/home/build/citools/bin
  SITE: fmrsn.com
tasks:
  - build: |
      cd "$SITE"
      ./build.sh
  - package: |
      cd "$SITE"/public
      tar -czf ../site.tar.gz .
  - deploy: |
      cd "$SITE"
      hut pages publish -d "$SITE" site.tar.gz
triggers:
  - action: email
    condition: failure
    to: F. Emerson <fmrsn@fmrsn.com>
