#!/bin/sh -eu

asdatauri() {
	mime=$(file -b --mime-type "$1")
	printf 'data:%s;base64,' "$mime"
	openssl base64 -e -A -in "$1"
}

rm -rf public
cp -r static public
cd public

favicon=$(asdatauri ../templates/favicon.png)
avatar=$(asdatauri ../templates/avatar.jpg)

sed \
	-e "s|@avatar@|$avatar|g" \
	-e "s|@favicon@|$favicon|g" \
	../templates/index.html >index.html
sed \
	-e "s|@lastmod@|$(date -u +%F)|g" \
	../templates/sitemap.xml >sitemap.xml

chmod -R 0644 *
minify -ro . .
